# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 05:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='article',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='article',
            name='pub_date',
        ),
    ]
